sources:
  - name: GeneralSettingAPI
    handler:
      jsonSchema:
        baseUrl: "{env.VPC_API_BASE_URL}"
        operationHeaders:
          # Please do not use capital letters while getting the headers
          Authorization: "{env.AUTH_TOKEN}"
        operations:
          - type: Query
            field: task_inbox_count
            path: /task_inbox_count
            method: GET
            responseSchema: ./json-schemas/inbox_count.json#/definitions/InboxCount
          - type: Query
            field: community_general_settings
            path: /community_general_settings
            method: GET
            responseSchema: ./json-schemas/gs.json#/definitions/CommunityGeneralSetting
  - name: General Setting
    handler:
      openapi:
        source: ./openapi-spec/gs.yml
        ignoreErrorResponses: true
        baseUrl: "{env.VPC_API_BASE_URL}"
        operationHeaders:
          # Please do not use capital letters while getting the headers
          Authorization: "{env.AUTH_TOKEN}"
  - name: Records API
    handler:
      openapi:
        source: ./openapi-spec/records.yml
        ignoreErrorResponses: true
        baseUrl: "{env.VPC_API_BASE_URL}"
        operationHeaders:
          # Please do not use capital letters while getting the headers
          Authorization: "{env.AUTH_TOKEN}"
  - name: User API
    handler:
      openapi:
        source: ./openapi-spec/user.yml
        ignoreErrorResponses: true
        baseUrl: "{env.VPC_API_BASE_URL}"
              

documents:
  - ./example-queries/*.graphql

serve:
  playground: true
