sources:
  - name: General Setting API
    handler:
      jsonSchema:
        baseUrl: "{env.VPC_API_BASE_URL}"
        operationHeaders:
          # Please do not use capital letters while getting the headers
          Authorization: "{env.AUTH_TOKEN}"
        operations:
          - type: Query
            field: general_settings
            path: /general_settings/1
            method: GET
            responseSample: ./json-schemas/gs.json
  - name: Records API
    handler:
      openapi:
        source: ./openapi-spec/records.yml
        ignoreErrorResponses: true
        baseUrl: "{env.VPC_API_BASE_URL}"
        operationHeaders:
          # Please do not use capital letters while getting the headers
          Authorization: "{env.AUTH_TOKEN}"

documents:
  - ./example-queries/*.graphql

serve:
  playground: true
