openapi: 3.0.2
info:
  version: 0.0.1
  title: Citizen services communities general settings 
paths:
  /general_settings/{id}:
    get:
      summary: Returns general setting
      operationId: getGeneralSettings
      tags:
        - GeneralSettings
      parameters:
        - name: id
          in: path
          description: ID parameter
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: General Setting Details
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/general_settings'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    general_settings:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: integer
            attributes:
              type: object
              properties:
                generalSettingsID:
                  type: integer
                orgName:
                  type: string
                logoURL:
                  type: string
                addressIntegration:
                  type: boolean
                allowTestPayments:
                  type: boolean
                stripeConnected:
                  type: boolean
                stripeLive:
                  type: boolean
                lastUpdatedDate:
                  type: string
                  format: date-time
                mapDefaultLatitude:
                  type: string
                mapDefaultLongitude:
                  type: string
                timeZoneName:
                  type: string 

 
     